# .mise.toml
[tools]
lg = "1.7.4"
lgx = "0.1.0-alpha3"
cljfmt = "0.16.4"
clojure = "1.12.4.1629"
babashka = "1.12.218"
java = "temurin-21.0.2+13.0.LTS"

[tool_alias]
lg = "github:nooga/let-go"
lgx = "github:abogoyavlensky/lgx"
cljfmt = "asdf:https://github.com/b-social/asdf-cljfmt"
